In [ ]:
#########################   PYTHON ---- NUMPY --------- ######################################




In [4]:
#Numpy Basic Operations

#import numpy library with alias np

import numpy as np

# creating an array 

a = np.array([1,2,3,4])

#prints a variable

print(a)

[1 2 3 4]


In [4]:
#To print the type of a variable

print (type(a))

<class 'numpy.ndarray'>


In [11]:
print(a.shape)

(4,)


In [6]:
print(a[1])

2


In [19]:
a2darray = np.array([[1,2,3],[4,5,6]])

print(a2darray)
print(a2darray.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
print(type(a2darray))

<class 'numpy.ndarray'>


In [7]:
b = np.array([1,2,3,4.5565])

In [8]:
b.dtype

dtype('float64')

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [30]:
np.ones((1,3))

array([[ 1.,  1.,  1.]])

In [71]:
np.empty((1,4))

array([[ 1.,  1.,  1.,  1.]])

In [67]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [63]:
axisVariable = np.array([[1,2,3],[4,5,6]])

In [22]:
# Sum the array in one to one fashion

axisVariable.sum(axis=0)

array([5, 7, 9])

In [23]:
#Sum the array in collective fashion

axisVariable.sum(axis=1)

array([ 6, 15])

In [24]:
# To find the Square root

np.sqrt(axisVariable)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [33]:
np.diag((1,2,3,5,6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [5]:
s = np.array([[1,2,3],[2,4]])


In [10]:
s.ndim

1

In [37]:
s.itemsize

8

In [39]:
axisVariable.size

6

In [44]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],np.float32)

d = c.reshape(4,4)

In [45]:
print(d)

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]]


In [46]:
d.dtype

dtype('float32')

In [47]:
d

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.]], dtype=float32)

In [52]:
d[1:,1:]

array([[  6.,   7.,   8.],
       [ 10.,  11.,  12.],
       [ 14.,  15.,  16.]], dtype=float32)

In [57]:
d[:1,:]

array([[ 1.,  2.,  3.,  4.]], dtype=float32)

In [ ]:
#Find the range

# range(start,stop,steps)

print(list(range(1,10,3)))

In [60]:
np.random.rand(5,5)

print(np.random.rand.__doc__)

array([[ 0.75980418,  0.8027378 ,  0.48062997,  0.89319237,  0.70835925],
       [ 0.16047365,  0.38614463,  0.35296557,  0.78695746,  0.45250702],
       [ 0.02220753,  0.19863179,  0.89887701,  0.33111608,  0.79902961],
       [ 0.26949042,  0.76928328,  0.44060691,  0.57578283,  0.76254115],
       [ 0.51589666,  0.76389858,  0.4867475 ,  0.90835068,  0.28652027]])

In [80]:
import csv
with open("winequality-red.csv", 'r') as f:
   wines = list(csv.reader(f, delimiter=";"))
print(wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


[['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'],
 ['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.8',
  '0.88',
  '0',
  '2.6',
  '0.098',
  '25',
  '67',
  '0.9968',
  '3.2',
  '0.68',
  '9.8',
  '5']]

In [81]:
type(wines)

list

In [82]:
print(wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [84]:
#for item in wines[1:]:
 #   print(item[-1])
len(wines)

1600

In [85]:
import numpy as np
wines = np.array(wines[1:], dtype=np.float)
wines


array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [86]:
wines.shape


(1599, 12)

In [97]:
np.transpose(wines).shape
#

(12, 1599)

In [101]:
# Original Wines

print(wines)

# Flattened ravel wines

wines.ravel()

[[  7.40000000e+00   7.00000000e-01   0.00000000e+00 ...,   5.60000000e-01
    5.00000000e+01   5.00000000e+00]
 [  7.80000000e+00   8.80000000e-01   0.00000000e+00 ...,   6.80000000e-01
    5.00000000e+01   5.00000000e+00]
 [  7.80000000e+00   7.60000000e-01   4.00000000e-02 ...,   6.50000000e-01
    5.00000000e+01   5.00000000e+00]
 ..., 
 [  6.30000000e+00   5.10000000e-01   1.30000000e-01 ...,   7.50000000e-01
    5.00000000e+01   6.00000000e+00]
 [  5.90000000e+00   6.45000000e-01   1.20000000e-01 ...,   7.10000000e-01
    5.00000000e+01   5.00000000e+00]
 [  6.00000000e+00   3.10000000e-01   4.70000000e-01 ...,   6.60000000e-01
    5.00000000e+01   6.00000000e+00]]


array([  7.4 ,   0.7 ,   0.  , ...,   0.66,  50.  ,   6.  ])