In [310]:
import numpy as np
import os 

In [312]:
pwd = os.getcwd()
print(pwd)

C:\Users\support


In [321]:
a= 5
b =7
print(a+b)
print(a-b)
print(a*b)
print(a ** b)
print(7 % 2)

12
-2
35
78125
1


In [313]:
x = 5
print (x)

x +=7

print (x)


5
12


In [26]:
pi = 3.1415
print(pi)

3.1415


In [324]:
T= True
print (type(T))


<class 'bool'>


In [37]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print len(hello)

SyntaxError: invalid syntax (<ipython-input-37-9e6a06a715a1>, line 3)

In [255]:
temp = 'Hello' + ' ' +'World'
print (temp)

Hello World


In [51]:
s = "  hello  "
print (s.capitalize()) #.capitalize()  # Capitalize a string
print(s.upper())
print (s.strip())  # Strip leading and trailing whitespace


  hello  
  HELLO  
hello


In [55]:
firstString = 'I am '
secondString = 'from INSOFE Batch'
batchno = " 32 "
a = firstString  + secondString + batchno
a.upper()

'I AM FROM INSOFE BATCH 32 '

In [59]:
     # Data Formatting
    
re = '%s %s %d' % ('I am', 'from ML Batch', 32)
type(re)
#print type(re)

str

In [63]:

xs = [3, 1, 2]   # Create a list
print (xs)
print (xs[2])
print (xs[-1], xs[-2], xs[-3] )    # Negative indices count from the end of the list; prints "2"

[3, 1, 2]
2
2 1 3


In [66]:
xs[2] = 'foo'
xs.append('bar') # Add a new element to the end of the list
xs

[3, 1, 'foo', 'bar', 'bar']

In [68]:
from IPython.display import Image
Image(filename='list.png')

FileNotFoundError: [Errno 2] No such file or directory: 'list.png'

In [73]:
str_list = ["a","b","c","d","e","f"]
print (str_list)
str_list[-1]

['a', 'b', 'c', 'd', 'e', 'f']


'f'

In [78]:
print (str_list[2:4])    # Get a slice from index 2 to 4 (exclusive)
print (str_list[2:])     # Get a slice from index 2 to the end
print (str_list[:2])     # Get a slice from the start to index 2 (exclusive)
print (str_list[:])      # Get a slice of the whole list
print (str_list[:-1])    # Slice indices can be negative

['c', 'd']
['c', 'd', 'e', 'f']
['a', 'b']
['a', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e']


In [86]:
number = range(5)    # range is a built-in function that creates a list of integers
print (number)


range(0, 5)


In [94]:
x = int(raw_input("Please enter an integer: "))

if x < 0:
    x = 0
    print('Negative changed to zero')

NameError: name 'raw_input' is not defined

In [120]:
a = range(20,31)
a
for i in a:
    if i % 2!=0:
        print (i)
        

21
23
25
27
29


             ######       ########   List Comprehension    #########

In [121]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print (squares)

square = [ x ** 2 for x in nums]
print (square)

nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]


In [128]:
var1 = range(1,6)
var2 = range(10,21)
var3 = []
for i in var1:
  for j in var2:
    if((i+j)%3 == 0):
     var3.append(i+j)
print(var3)

[12, 15, 18, 21, 12, 15, 18, 21, 15, 18, 21, 15, 18, 21, 24, 15, 18, 21, 24]


In [257]:
var1 = range(1,6)
var2 = range(10,21)
var3 = [(i+j) for i in var1 for j in var2 if (i+j)%3 ==0]
print(var3)
print(var3[5])

[12, 15, 18, 21, 12, 15, 18, 21, 15, 18, 21, 15, 18, 21, 24, 15, 18, 21, 24]
15


             ###### ##########   Dictionary  ################

In [147]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
f = {'1':'Small','2':'big'}
print (f['1'])
print (d['cat'])       # Get an entry from a dictionary; prints "cute"
print ('cat' in d)    # Check if a dictionary has a given key; prints "True"
f['1'] = 'Very Samll'
print (f)
# f.append['3':'large']

Small
cute
True
{'1': 'Very Samll', '2': 'big'}


In [151]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print ('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [159]:
d = {'person': 2, 'cat': 4, 'spider': 8}
print (['A %s has %d legs' % (animal , d[animal]) for animal in d])

['A person has 2 legs', 'A cat has 4 legs', 'A spider has 8 legs']


In [166]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print (even_num_to_square)

{0: 0, 2: 4, 4: 16}


In [178]:
t = (2,6)
print (type(t))

f = [2,3,4]
f.append(5)
print (f)
print (type(f))

<class 'tuple'>
[2, 3, 4, 5]
<class 'list'>


In [192]:

i = range(1,5)
j = range (1,2)
result = []
for i1 in i:
  for j1 in j:
        result.append(i1+j1)
        print(result)
        
var1 = range(1,6)
print(type(var1))
var2 = range(10,21)
var3 = []
for i in var1:
  for j in var2:
    if((i+j)%3 == 0):
     var3.append(i+j)
print(var3)

[2]
[2, 3]
[2, 3, 4]
[2, 3, 4, 5]
<class 'range'>
[12, 15, 18, 21, 12, 15, 18, 21, 15, 18, 21, 15, 18, 21, 24, 15, 18, 21, 24]


In [ ]:
  #######    Function

In [259]:

##Python functions are defined using the def keyword. For example:

def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print (sign(x))

negative
zero
positive


In [268]:
##We will often define functions to take optional keyword arguments, like this:

def hello(name, loud=False):
    if loud: 
        print ('HELLO, %s' % name.upper()) 
    else: 
        print ('Hello, %s' % name)

hello('Bob') 
hello('Fred', loud=True)

Hello, Bob
HELLO, FRED


In [ ]:
##Lambda Function

In [274]:
f = lambda x, y : x + y
f(1,1)

#This is equivalent to 
#def f (x,y):
 #   print return(x+y)

2

In [ ]:
  ##Map Function

In [ ]:
The map() Function
map() is a function with two arguments:

r = map(func, seq)

The first argument func is the name of a function and the second a sequence (e.g. a list) seq. map() applies the function func to all the elements of the sequence seq. 
It returns a new list with the elements changed by func

In [291]:
def fahrenheit(T):
    return ((float(9)/5)*T + 32)

def celsius(T):
    return (float(5)/9)*(T-32)

temp = (36.5, 37, 37.5,39)

F = list(map(fahrenheit, temp))
print (F)

C = list(map(celsius, F))
print (C)

[97.7, 98.60000000000001, 99.5, 102.2]
[36.5, 37.00000000000001, 37.5, 39.0]


In [283]:
## Filter

In [296]:
fib = [0,1,1,2,3,5,8,13,21,34,55]
result = list(filter(lambda x: x % 2, fib))
print (result)

[1, 1, 3, 5, 13, 21, 55]


In [ ]:
      #####################   NUMPY    ##############################

In [3]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5]) 

In [5]:
type(a1)

numpy.ndarray

In [20]:
a = np.arange(15)
print(a)
print(a.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


In [21]:
## Reshaping of Array
a1 = np.arange(15).reshape(3, 5)
print(a1)
print(a1.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


In [26]:
a2 = np.arange(10).reshape(5,2)
print(a2)
#flatten 
print(a2.flatten())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [29]:
## Stack
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:', np.vstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [71]:
## Slice
e  = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
print(e)
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Second row: [5 6 7 8]


In [72]:
#In Python, like many other languages,

#The values before the comma stand for the rows
#The value on the rights stands for the columns.
#If you want to select a column, you need to add : before the column index.
#: means you want all the rows from the selected column.

print('Second column:', e[:,1])
print(e[1, :2])
print ("Entire table " , e[:,:])
# Accessing 2nd row with column 1 till end
print ("Accessing Rowise", e[2,1:])
print(e[0:2,0:1])

Second column: [ 2  6 10]
[5 6]
Entire table  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Accessing Rowise [10 11 12]
[[1]
 [5]]


In [297]:
normal_array = [10,20,50,100,200]

## Statistical function
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))
### Mean 
print(np.mean(normal_array))
### Median
print(np.median(normal_array))
### Sd
print(np.std(normal_array))

10
200
76.0
50.0
69.45502141674135


In [302]:
from numpy import *  
import time
def trad_version():
    t1 = time.time()
    X = range (10000000)
    Y = range (10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i]) 
    return time.time() - t1
print(trad_version())

5.424310207366943


In [288]:
def numpy_version(): 
    t1 = time.time()
    X = arange (10000000)
    Y = arange (10000000)
    Z=X+Y
    return time.time() - t1
print(numpy_version())

0.055005550384521484


In [63]:
numpArray = arange(9).reshape(3,3)
print (numpArray)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [66]:
farenheit_converted = numpArray *9 /2
print(farenheit_converted)

[[ 0.   4.5  9. ]
 [13.5 18.  22.5]
 [27.  31.5 36. ]]


In [ ]:
 ### PANDAS

In [194]:
import pandas as pd
import numpy as np

In [285]:
s = pd.Series([1,3,5,np.nan,6,8])
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [200]:
dates = pd.date_range('20130101', periods=12)
print(type(dates))
print(dates)
pd.date_range('20130101',periods=5)

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12'],
              dtype='datetime64[ns]', freq='D')


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05'],
              dtype='datetime64[ns]', freq='D')

In [211]:
df2 = pd.DataFrame({'Rank' : range(1,6),
        'Date' : pd.date_range('20130102', periods=5),
        'Score' : range(5,0,-1),
        'Category' : pd.Categorical(["Distinction","First","Second","Average","Below Average"]),
        'Name' : ('foo','Boo','Moo','Noo','Doo')})
print(df2)
#slicing using Index
print(df2['Date'])
print(df2['Name'])
print(df2[0:3]) #slicing via rows index sliced o to 3 row
#print(df2.loc[0:3,]) # fetches row 0,1,2 
print(df2[2:4])

   Rank       Date  Score       Category Name
0     1 2013-01-02      5    Distinction  foo
1     2 2013-01-03      4          First  Boo
2     3 2013-01-04      3         Second  Moo
3     4 2013-01-05      2        Average  Noo
4     5 2013-01-06      1  Below Average  Doo
0   2013-01-02
1   2013-01-03
2   2013-01-04
3   2013-01-05
4   2013-01-06
Name: Date, dtype: datetime64[ns]
0    foo
1    Boo
2    Moo
3    Noo
4    Doo
Name: Name, dtype: object
   Rank       Date  Score     Category Name
0     1 2013-01-02      5  Distinction  foo
1     2 2013-01-03      4        First  Boo
2     3 2013-01-04      3       Second  Moo
   Rank       Date  Score Category Name
2     3 2013-01-04      3   Second  Moo
3     4 2013-01-05      2  Average  Noo


In [213]:
#Dimensionality Reduction
#loc - loc[rowstart:rowend, [column names]]
#All 3 statements are same - fetch all the rows and columns
print(df2.loc[:,:])
print(df2.loc[:,])
print(df2.loc[:])

#fetch all rows with these 3 columns
print("\n ===fetch all rows with these 3 columns===")
print(df2.loc[:,['Date','Name','Rank']])

#fetch first 3 rows with these 3 colums 
print("\n ===fetch first 3 rows with these 3 colums===")
print(df2.loc[0:3,['Date','Name','Rank']])

#iloc - iloc[rowstart_index:rowend_index,columnstart_index:columnend_index]
#All 3 statements are same
print(df2.iloc[:,:])
print(df2.iloc[:,])
print(df2.iloc[:])

#fetch all rows with these 3 columns index
print(df2.iloc[:,1:4])
print("\n ===fetch first 3 rows with these 3 colums===")
print(df2.iloc[0:3,1:4])

   Rank       Date  Score       Category Name
0     1 2013-01-02      5    Distinction  foo
1     2 2013-01-03      4          First  Boo
2     3 2013-01-04      3         Second  Moo
3     4 2013-01-05      2        Average  Noo
4     5 2013-01-06      1  Below Average  Doo
   Rank       Date  Score       Category Name
0     1 2013-01-02      5    Distinction  foo
1     2 2013-01-03      4          First  Boo
2     3 2013-01-04      3         Second  Moo
3     4 2013-01-05      2        Average  Noo
4     5 2013-01-06      1  Below Average  Doo
   Rank       Date  Score       Category Name
0     1 2013-01-02      5    Distinction  foo
1     2 2013-01-03      4          First  Boo
2     3 2013-01-04      3         Second  Moo
3     4 2013-01-05      2        Average  Noo
4     5 2013-01-06      1  Below Average  Doo

 ===fetch all rows with these 3 columns===
        Date Name  Rank
0 2013-01-02  foo     1
1 2013-01-03  Boo     2
2 2013-01-04  Moo     3
3 2013-01-05  Noo     4
4 2013-0

In [215]:
#fetch all rows with these 3 columns (LOC fetches inclusive of indexes)
print("\n ===fetch all rows with these 3 columns===")
print(df2.loc[:,['Date','Name','Rank']])

#fetch first 3 rows with these 3 colums 
print("\n ===fetch first 4 rows with these 3 colums===")
print(df2.loc[0:3,['Date','Name','Rank']])
print(df2.loc[0:3,'Date':'Rank'])

#fetch first 3 rows with these 3 colums 
print("\n ===fetch first 4 rows with all colums===")
print(df2.loc[0:3,])

#fetch all rows with these 3 columns index
print("\n ===fetch all rows with these 3 columns===")
print(df2.iloc[:,1:4])
print("\n ===fetch first 3 rows with these 3 colums===")
print(df2.iloc[0:3,1:4])
print("\n ===fetch first 3 rows with these colums===")
print(df2.iloc[0:3,:])


 ===fetch all rows with these 3 columns===
        Date Name  Rank
0 2013-01-02  foo     1
1 2013-01-03  Boo     2
2 2013-01-04  Moo     3
3 2013-01-05  Noo     4
4 2013-01-06  Doo     5

 ===fetch first 4 rows with these 3 colums===
        Date Name  Rank
0 2013-01-02  foo     1
1 2013-01-03  Boo     2
2 2013-01-04  Moo     3
3 2013-01-05  Noo     4
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

 ===fetch first 4 rows with all colums===
   Rank       Date  Score     Category Name
0     1 2013-01-02      5  Distinction  foo
1     2 2013-01-03      4        First  Boo
2     3 2013-01-04      3       Second  Moo
3     4 2013-01-05      2      Average  Noo

 ===fetch all rows with these 3 columns===
        Date  Score       Category
0 2013-01-02      5    Distinction
1 2013-01-03      4          First
2 2013-01-04      3         Second
3 2013-01-05      2        Average
4 2013-01-06      1  Below Average

 ===fetch first 3 rows with these 3 colums===
        Date  Score     Category


In [239]:
#selective fetching based on Name
print(df2.loc[(df2.Name == "Boo") | (df2.Name == "Moo"), :])

#applying lambda in the dataframe
df2.loc[df2['Category'].apply(lambda x:len(x) > 8)]


   Rank       Date  Score Category Name
1     2 2013-01-03      4    First  Boo
2     3 2013-01-04      3   Second  Moo


Rank       Date  Score       Category Name
0     1 2013-01-02      5    Distinction  foo
4     5 2013-01-06      1  Below Average  Doo

In [240]:
#creating a dataframe:

raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'last_name': ['Miller', 'Jacobson', ".", 'Milner', 'Cooze'], 
        'age': [42, 52, 36, 24, 73], 
        'preTestScore': [4, 24, 31, ".", "."],
        'postTestScore': ["25,000", "94,000", 57, 62, 70]}

#print (type(raw_data))
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'preTestScore', 'postTestScore'])
# df = df.loc[1:, df['age'].apply(lambda x: int(x) > 20)] 
df


first_name last_name  age preTestScore postTestScore
0      Jason    Miller   42            4        25,000
1      Molly  Jacobson   52           24        94,000
2       Tina         .   36           31            57
3       Jake    Milner   24            .            62
4        Amy     Cooze   73            .            70

In [241]:
# fetching all the names whose age is greater than 50
df = df.loc[1:] 
df.loc[df['Age'].apply(lambda x: int(x)>40),"First Name":"Age"]

KeyError: 'Age'

######  PANDAS  

In [243]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5]) 

In [244]:
type(a1)

numpy.ndarray

In [250]:
a = np.arange(15)
print (a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


In [251]:
## Slice
e  = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
print(e)
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Second row: [5 6 7 8]


In [309]:
###########  How to import from CSV to DataFrame

import pandas as pd
import numpy as np
import os 

pwd = os.getcwd()

print(pwd)

data = pd.read_csv("annual-balance-sheet-2007-16-provisional-csv-tables.csv")
data.to_html("CSV_HTML.html")



C:\Users\support
