In [3]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5]) 

In [5]:
type(a1)

numpy.ndarray

In [20]:
a = np.arange(15)
print(a)
print(a.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


In [21]:
a1 = np.arange(15).reshape(3, 5)
print(a1)
print(a1.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


In [26]:
a2 = np.arange(10).reshape(5,2)
print(a2)
#flatten 
print(a2.flatten())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [29]:
## Stack
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:', np.vstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [71]:
## Slice
e  = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
print(e)
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Second row: [5 6 7 8]


In [72]:
#In Python, like many other languages,

#The values before the comma stand for the rows
#The value on the rights stands for the columns.
#If you want to select a column, you need to add : before the column index.
#: means you want all the rows from the selected column.

print('Second column:', e[:,1])
print(e[1, :2])
print ("Entire table " , e[:,:])
# Accessing 2nd row with column 1 till end
print ("Accessing Rowise", e[2,1:])
print(e[0:2,0:1])

Second column: [ 2  6 10]
[5 6]
Entire table  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Accessing Rowise [10 11 12]
[[1]
 [5]]


In [53]:
normal_array = [10,20,50,100,200]

## Statistical function
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))
### Mean 
print(np.mean(normal_array))
### Median
print(np.median(normal_array))
### Sd
print(np.std(normal_array))

10
200
76.0
50.0
69.45502141674135


In [58]:
from numpy import *  
import time
def trad_version():
    t1 = time.time()
    X = range (10000000)
    Y = range (10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i]) 
    return time.time() - t1
print(trad_version())

3.48751163482666


In [59]:
def numpy_version(): 
    t1 = time.time()
    X = arange (10000000)
    Y = arange (10000000)
    Z=X+Y
    return time.time() - t1
print(numpy_version())

0.11584782600402832


In [63]:
numpArray = arange(9).reshape(3,3)
print (numpArray)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [66]:
farenheit_converted = numpArray *9 /2
print(farenheit_converted)

[[ 0.   4.5  9. ]
 [13.5 18.  22.5]
 [27.  31.5 36. ]]
